runtime: nodejs18
env: static

handlers:
  - url: /api/.*
    script: auto
    secure: always

  - url: /(.*\.(js|css|png|jpg|jpeg|gif|svg|ico|woff|woff2|ttf|eot))
    static_files: dist/\1
    upload: dist/(.*\.(js|css|png|jpg|jpeg|gif|svg|ico|woff|woff2|ttf|eot))
    http_headers:
      Cache-Control: 'public, max-age=31536000, immutable'

  - url: /(.*)
    static_files: dist/index.html
    upload: dist/index.html
    http_headers:
      X-Frame-Options: DENY
      X-Content-Type-Options: no-sniff
      X-XSS-Protection: '1; mode=block'
      Referrer-Policy: no-referrer-when-downgrade

env_variables:
  NODE_ENV: production
