runtime: nodejs18
service: shababna-frontend

handlers:
  # API proxy
  - url: /api/.*
    script: auto
    secure: always

  # Static assets with caching
  - url: /assets/.*
    static_dir: dist/assets
    secure: always
    http_headers:
      Cache-Control: 'public, max-age=31536000, immutable'

  - url: /.*\.(js|css|png|jpg|svg|ico|woff|woff2|ttf|eot)
    static_files: dist/\1
    upload: dist/.*\.(js|css|png|jpg|svg|ico|woff|woff2|ttf|eot)
    secure: always
    http_headers:
      Cache-Control: 'public, max-age=31536000, immutable'

  # SPA routing - serve index.html for all other routes
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always
    http_headers:
      X-Frame-Options: 'DENY'
      X-Content-Type-Options: 'nosniff'
      X-XSS-Protection: '1; mode=block'
      Referrer-Policy: 'no-referrer-when-downgrade'
      Cache-Control: 'no-cache, no-store, must-revalidate'

env_variables:
  NODE_ENV: 'production'
