// قائمة دول العالم (عربي - إنجليزي)
export const countries = [
  { code: 'SA', ar: 'المملكة العربية السعودية', en: 'Saudi Arabia' },
  { code: 'EG', ar: 'مصر', en: 'Egypt' },
  { code: 'AE', ar: 'الإمارات العربية المتحدة', en: 'United Arab Emirates' },
  { code: 'KW', ar: 'الكويت', en: 'Kuwait' },
  { code: 'QA', ar: 'قطر', en: 'Qatar' },
  { code: 'OM', ar: 'عمان', en: 'Oman' },
  { code: 'BH', ar: 'البحرين', en: 'Bahrain' },
  { code: 'JO', ar: 'الأردن', en: 'Jordan' },
  { code: 'LB', ar: 'لبنان', en: 'Lebanon' },
  { code: 'SY', ar: 'سوريا', en: 'Syria' },
  { code: 'IQ', ar: 'العراق', en: 'Iraq' },
  { code: 'YE', ar: 'اليمن', en: 'Yemen' },
  { code: 'MA', ar: 'المغرب', en: 'Morocco' },
  { code: 'TN', ar: 'تونس', en: 'Tunisia' },
  { code: 'DZ', ar: 'الجزائر', en: 'Algeria' },
  { code: 'SD', ar: 'السودان', en: 'Sudan' },
  { code: 'LY', ar: 'ليبيا', en: 'Libya' },
  { code: 'PS', ar: 'فلسطين', en: 'Palestine' },
  { code: 'TR', ar: 'تركيا', en: 'Turkey' },
  { code: 'US', ar: 'الولايات المتحدة', en: 'United States' },
  { code: 'GB', ar: 'المملكة المتحدة', en: 'United Kingdom' },
  { code: 'FR', ar: 'فرنسا', en: 'France' },
  { code: 'DE', ar: 'ألمانيا', en: 'Germany' },
  { code: 'IT', ar: 'إيطاليا', en: 'Italy' },
  { code: 'ES', ar: 'إسبانيا', en: 'Spain' },
  { code: 'CA', ar: 'كندا', en: 'Canada' },
  { code: 'IN', ar: 'الهند', en: 'India' },
  { code: 'CN', ar: 'الصين', en: 'China' },
  { code: 'JP', ar: 'اليابان', en: 'Japan' },
  { code: 'RU', ar: 'روسيا', en: 'Russia' },
  // ... أضف باقي الدول حسب الحاجة أو استورد قائمة كاملة لاحقاً
];